name: itmchat
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


flutter_statusbarcolor_ns: 0.3.0-nullsafety
flutter_webview_plugin: 0.4.0
notification_permissions: 0.5.0
onesignal_flutter: 3.2.0
sms_autofill: 2.0.1



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.9
  qr_flutter: ^4.0.0
  flutter_barcode_scanner:
  firebase_auth: ^3.3.16
  google_sign_in:
  shared_preferences:
  random_string:
  cloud_firestore: ^3.1.13
  firebase_core: ^1.16.0
  stream_chat_flutter: ^4.0.0
  flutter_html:
  webview_flutter: ^3.0.2
flutter_svg:
webview_flutter: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
     
  intl: ^0.17.0
  animations: ^2.0.2
  xml: ^5.3.1
  xml2json: ^5.3.2
  webfeed: ^0.7.0
  url_launcher: ^6.0.18
  cached_network_image: ^3.2.0
  ionicons: ^0.1.2
  flutter_launcher_icons: ^0.9.2
  http: ^0.13.4
  flutter_phone_direct_caller: ^2.1.1


  flutter_lints: ^1.0.0



flutter:

  uses-material-design: true
  assets:
    - assets/images/splash.jpg

